version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: lnpr-lnpayroll_server_1
      APP_PORT: 8088
      PROXY_AUTH_ADD: "false"

  server:
    image: ghcr.io/titusz/lnpayroll:latest
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}:/data
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro
    environment:
      AUTO_MIGRATE_AND_INSTALL: "true"
      SECRED_KEY: $APP_SEED
      LNPAYROLL_DATA_DIR: "/data"
      LNPAYROLL_DB_URI: sqlite:////data/lnpayroll.sqlite
      LND_REST_URL: https://$APP_LIGHTNING_NODE_IP:$APP_LIGHTNING_NODE_REST_PORT/

